### ISSUE TITLE
[feature] Interactive Raw Data JSON

### ISSUE THREAD

**Issue by smirea** [mozilla/fhr-jelly#148]
I've been working a lot with FHR and having to always look at the Raw Data tab gets tiring when dumping a huge plain json object as text all day long. 

I made a greasemonkey extension to colorize and add folding to the JSON there (see attached gif) and figured this might be useful for more people (maybe with a different style? ) if an iteration of this would be part of the actual about:healthreport page so I wanted to get your opinion on this

![fhr-raw-data](https://f.cloud.github.com/assets/544097/1168951/5776ba28-20a9-11e3-978d-49ce327a8a46.gif)

**Comment by georgf** [comment]
After we switched about:healthreport to be backed by Telemetry, about:telemetry is the better way to look at the data in a structured way.
