### ISSUE TITLE
Inline templated (and mutating) JS makes use of CSP difficult

### ISSUE THREAD

**Issue by april** [mozilla/fhr-jelly#182]
This piece of code here:

https://github.com/mozilla/fhr-jelly/blob/master/templates/v4.html#L188

Uses a templates to fill in `{{ _("ON") }}`, for example. It says it has to be inline, but is there a reason why we can't:

1) move it to an external script (or JSON)
2) update generate.py to modify that particular piece of JS or JSON

**Comment by floatingatoll** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1371690

**Comment by georgf** [comment]
This feature was removed from Firefox and this repositories code is effectively frozen.
Closing.
